### ISSUE TITLE
Can't parse aws outputs

### ISSUE THREAD

**Issue by danbdo** [corydozen/serverless-cdk-cicd#1]
Hey,

I am trying to follow along here. Works nicely so far, apart from a couple of glitches in the pages of various steps (hope to find some time to PR fixes soon).
Where I am stuck right now is parseAwsOutputs.js not being able to parse the files. I am not quite sure what is going on. Maybe cdk has changed the output so that the parser gets stuck?
It fails when trying to read individual lines where it seems to expect to find a key=value structure. But the files I have only have individual ARNs per line. 
I am not quite sure how config.js is supposed to look like so I can't quite fix this myself.

**Comment by corydozen** [comment]
Thanks for opening the first issue!

No, the cdk output hasn't changed. I'm still using this same `parseAwsOutputs.js` file and it's working for me in other projects.

Could you share your cdkdeployresult_appsync.txt and/or cdkdeployresult_cognito.txt file(s)? Be sure to redact any info you don't want to share.

**Comment by danbdo** [comment]
Hey, 
the ..appsync.. file has
```
arn:aws:cloudformation:(region):(account):stack/DynamoDb/e1bbb5a0-fbf7-11e9-9ea2-0a43c0b04aee
arn:aws:cloudformation:(region):(account):stack/Cognito/bbffcfc0-fbfe-11e9-9592-06bc90058f1a
arn:aws:cloudformation:(region):(account):stack/AppSync/872fc900-ffda-11e9-9e61-0ac843449136
```

The ..cognito.. file has
```
arn:aws:cloudformation:(region):(account):stack/DynamoDb/e1bbb5a0-fbf7-11e9-9ea2-0a43c0b04aee
arn:aws:cloudformation:(region):(account):stack/Cognito/bbffcfc0-fbfe-11e9-9592-06bc90058f1a
```

**Comment by corydozen** [comment]
It looks like maybe you left out the ampersand (`&`) in the `cdk deploy` command:

[cdk deploy TodoCognito --require-approval never **&**> ../cdkdeployresult_cognito.txt](https://github.com/corydozen/serverless-cdk-cicd/tree/master/11#blog-post-11---postman)

**Comment by danbdo** [comment]
Ah, very good hint!
I must admit I missed the ampersand. Secondly: That wouldn't work on a Windows machine anyway. So I had to figure out how the syntax has to look like to redirect the output properly.
Seems
```
cdk deploy TodoAppSync --profile own --require-approval never 1> ../cdkdeployresult_appsync.txt 2>&1
cdk deploy TodoCognito --profile own --require-approval never 1> ../cdkdeployresult_cognito.txt 2>&1
```
would work and this in fact gives me a proper config. But the seed for the config file is different as well.
Needs to be
`echo export default {}; > src/config.js`

**Comment by corydozen** [comment]
Aha! Thanks for that! I'll add that in for Windows users

**Comment by danbdo** [comment]
There might be more.. `npm run start` also doesn't work here.

```PORT=3333 react-scripts start

'PORT' is not recognized as an internal or external command```

**Comment by corydozen** [comment]
Hmm. Yes. Sorry I'm not as familiar with Windows. But it looks like you can use cross-env or create an env file to solve this problem. https://github.com/facebook/create-react-app/issues/1083#issuecomment-262170258

If you get this working, I'd love for you to add to the README on [Step 8](https://github.com/facebook/create-react-app/issues/1083#issuecomment-262170258) via a Pull Request
